---
# tasks file for rust

- name: Ensure rustup and cargo directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "/home/{{ username }}/.local/share/cargo"
    - "/home/{{ username }}/.local/share/rustup"

- name: Manage rust toolchain with rustup
  when: rust_installation_method == 'rustup'
  block:
    - name: Install rustup
      community.general.pacman:
        name: rustup
        state: "{{ rust_rustup_state }}"

- name: Install rust
  community.general.pacman:
    name: rust
    state: "{{ rust_state }}"
  when: rust_installation_method == 'rust'

  # rustup updates are disabled by this build, they are handled by pacman
- name: Check for rust updates
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: rustup check
  register: rust_rustup_check
  changed_when: rust_rustup_check.rc == 100
  failed_when: rust_rustup_check.rc not in [0, 100]
  notify: Update rust toolchain
  when: rust_installation_method == 'rustup' and rust_state != 'absent'

- name: Set default rust toolchain
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "rustup default {{ rust_rustup_default_toolchain }}"
  register: rust_rustup_default
  changed_when: "'unchanged' not in rust_rustup_default.stdout"
  when: rust_installation_method == 'rustup' and rust_state != 'absent'
