---
- name: Setup Arch Linux Gnome workstation
  hosts: workstation
  connection: local
  vars_files:
    - group_vars/all/vars.yaml
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Include selected roles
      ansible.builtin.include_role:
        name: "{{ role_item }}"
        apply:
          tags:
            - "{{ role_item }}"
      loop: "{{ roles_selected }}"
      loop_control:
        loop_var: role_item
      tags:
        - always
