---
- name: Setup Arch Linux Gnome workstation
  hosts: workstation
  connection: local
  vars_files:
    - group_vars/all/vars.yaml
  become: true
  become_user: root
  gather_facts: true

  roles:
    - role: aur_builder
      tags: [aur_builder]
      when: aur_builder_enabled | default(true)
    - role: pacman
      tags: [pacman]
      when: pacman_enabled | default(true)
    - role: zsh
      tags: [zsh]
      when: zsh_enabled | default(true)
    - role: fish
      tags: [fish]
      when: fish_enabled | default(true)
    - role: system
      tags: [system]
      when: system_enabled | default(true)
    # - role: nvidia
    #   tags: [nvidia]
    #   when: nvidia_enabled | default(true)
    - role: firmware
      tags: [firmware]
      when: firmware_enabled | default(true)
    - role: grub
      tags: [grub]
      when: grub_enabled | default(true)
    - role: fstrim
      tags: [fstrim]
      when: fstrim_enabled | default(true)
    - role: zram
      tags: [zram]
      when: zram_enabled | default(true)
    - role: user
      tags: [user]
      when: user_enabled | default(true)
    - role: ssh
      tags: [ssh]
      when: ssh_enabled | default(true)
    - role: multimedia
      tags: [multimedia]
      when: multimedia_enabled | default(true)
    - role: flatpak
      tags: [flatpak]
      when: flatpak_enabled | default(true)
    - role: fonts
      tags: [fonts]
      when: fonts_enabled | default(true)
    - role: gnome
      tags: [gnome]
      when: gnome_enabled | default(true)
    - role: nautilus
      tags: [nautilus]
      when: nautilus_enabled | default(true)
    - role: age
      tags: [age]
      when: age_enabled | default(true)
    - role: ansible
      tags: [ansible]
      when: ansible_enabled | default(true)
    - role: audacity
      tags: [audacity]
      when: audacity_enabled | default(true)
    - role: bat
      tags: [bat]
      when: bat_enabled | default(true)
    - role: beekeeper_studio
      tags: [beekeeper_studio]
      when: beekeeper_studio_enabled | default(true)
    - role: bitwarden
      tags: [bitwarden]
      when: bitwarden_enabled | default(true)
    - role: bleachbit
      tags: [bleachbit]
      when: bleachbit_enabled | default(true)
    # - role: blender
    #   tags: [blender]
    #   when: blender_enabled | default(true)
    - role: bruno
      tags: [bruno]
      when: bruno_enabled | default(true)
    - role: btop
      tags: [btop]
      when: btop_enabled | default(true)
    - role: czkawka
      tags: [czkawka]
      when: czkawka_enabled | default(true)
    - role: dconf_editor
      tags: [dconf_editor]
      when: dconf_editor_enabled | default(true)
    - role: delta
      tags: [delta]
      when: delta_enabled | default(true)
    - role: deno
      tags: [deno]
      when: deno_enabled | default(true)
    - role: direnv
      tags: [direnv]
      when: direnv_enabled | default(true)
    - role: discord
      tags: [discord]
      when: discord_enabled | default(true)
    - role: docker
      tags: [docker]
      when: docker_enabled | default(true)
    - role: dust
      tags: [dust]
      when: dust_enabled | default(true)
    - role: extension_manager
      tags: [extension_manager]
      when: extension_manager_enabled | default(true)
    - role: eza
      tags: [eza]
      when: eza_enabled | default(true)
    - role: fastfetch
      tags: [fastfetch]
      when: fastfetch_enabled | default(true)
    - role: fd
      tags: [fd]
      when: fd_enabled | default(true)
    - role: firefox
      tags: [firefox]
      when: firefox_enabled | default(true)
    - role: flatseal
      tags: [flatseal]
      when: flatseal_enabled | default(true)
    - role: fzf
      tags: [fzf]
      when: fzf_enabled | default(true)
    - role: gearlever
      tags: [gearlever]
      when: gearlever_enabled | default(true)
    - role: gh
      tags: [gh]
      when: gh_enabled | default(true)
    - role: ghostty
      tags: [ghostty]
      when: ghostty_enabled | default(true)
    - role: gimp
      tags: [gimp]
      when: gimp_enabled | default(true)
    - role: git
      tags: [git]
      when: git_enabled | default(true)
    - role: glow
      tags: [glow]
      when: glow_enabled | default(true)
    - role: go
      tags: [go]
      when: go_enabled | default(true)
    - role: google_chrome
      tags: [google_chrome]
      when: google_chrome_enabled | default(true)
    - role: handbrake
      tags: [handbrake]
      when: handbrake_enabled | default(true)
    - role: helix
      tags: [helix]
      when: helix_enabled | default(true)
    - role: helm
      tags: [helm]
      when: helm_enabled | default(true)
    - role: inkscape
      tags: [inkscape]
      when: inkscape_enabled | default(true)
    - role: jq
      tags: [jq]
      when: jq_enabled | default(true)
    - role: just
      tags: [just]
      when: just_enabled | default(true)
    - role: k3d
      tags: [k3d]
      when: k3d_enabled | default(true)
    - role: k9s
      tags: [k9s]
      when: k9s_enabled | default(true)
    - role: kanata
      tags: [kanata]
      when: kanata_enabled | default(true)
    - role: kde_connect
      tags: [kde_connect]
      when: kde_connect_enabled | default(true)
    # - role: kdenlive
    #   tags: [kdenlive]
    #   when: kdenlive_enabled | default(true)
    # - role: krita
    #   tags: [krita]
    #   when: krita_enabled | default(true)
    - role: ksops
      tags: [ksops]
      when: ksops_enabled | default(true)
    - role: kubectl
      tags: [kubectl]
      when: kubectl_enabled | default(true)
    - role: kubie
      tags: [kubie]
      when: kubie_enabled | default(true)
    - role: kustomize
      tags: [kustomize]
      when: kustomize_enabled | default(true)
    - role: lazydocker
      tags: [lazydocker]
      when: lazydocker_enabled | default(true)
    - role: lazygit
      tags: [lazygit]
      when: lazygit_enabled | default(true)
    - role: libreoffice
      tags: [libreoffice]
      when: libreoffice_enabled | default(true)
    - role: localsend
      tags: [localsend]
      when: localsend_enabled | default(true)
    - role: logseq
      tags: [logseq]
      when: logseq_enabled | default(true)
    - role: mkcert
      tags: [mkcert]
      when: mkcert_enabled | default(true)
    - role: ncdu
      tags: [ncdu]
      when: ncdu_enabled | default(true)
    - role: network_tools
      tags: [network_tools]
      when: network_tools_enabled | default(true)
    - role: nix
      tags: [nix]
      when: nix_enabled | default(true)
    - role: node
      tags: [node]
      when: node_enabled | default(true)
    # - role: obs
    #   tags: [obs]
    #   when: obs_enabled | default(true)
    - role: onefetch
      tags: [onefetch]
      when: onefetch_enabled | default(true)
    - role: pika_backup
      tags: [pika_backup]
      when: pika_backup_enabled | default(true)
    - role: protoc
      tags: [protoc]
      when: protoc_enabled | default(true)
    - role: python
      tags: [python]
      when: python_enabled | default(true)
    - role: qbittorrent
      tags: [qbittorrent]
      when: qbittorrent_enabled | default(true)
    - role: rclone
      tags: [rclone]
      when: rclone_enabled | default(true)
    - role: restic
      tags: [restic]
      when: restic_enabled | default(true)
    - role: ripgrep
      tags: [ripgrep]
      when: ripgrep_enabled | default(true)
    - role: rsync
      tags: [rsync]
      when: rsync_enabled | default(true)
    - role: rust
      tags: [rust]
      when: rust_enabled | default(true)
    - role: sd
      tags: [sd]
      when: sd_enabled | default(true)
    - role: slack
      tags: [slack]
      when: slack_enabled | default(true)
    - role: smartmontools
      tags: [smartmontools]
      when: smartmontools_enabled | default(true)
    - role: smile
      tags: [smile]
      when: smile_enabled | default(true)
    - role: sops
      tags: [sops]
      when: sops_enabled | default(true)
    - role: starship
      tags: [starship]
      when: starship_enabled | default(true)
    - role: syncthing
      tags: [syncthing]
      when: syncthing_enabled | default(true)
    - role: task
      tags: [task]
      when: task_enabled | default(true)
    - role: thunderbird
      tags: [thunderbird]
      when: thunderbird_enabled | default(true)
    - role: timeshift
      tags: [timeshift]
      when: timeshift_enabled | default(true)
    - role: tlrc
      tags: [tlrc]
      when: tlrc_enabled | default(true)
    - role: virtmanager
      tags: [virtmanager]
      when: virtmanager_enabled | default(true)
    - role: vlc
      tags: [vlc]
      when: vlc_enabled | default(true)
    - role: vscode
      tags: [vscode]
      when: vscode_enabled | default(true)
    - role: xh
      tags: [xh]
      when: xh_enabled | default(true)
    - role: yazi
      tags: [yazi]
      when: yazi_enabled | default(true)
    - role: yq
      tags: [yq]
      when: yq_enabled | default(true)
    - role: zed
      tags: [zed]
      when: zed_enabled | default(true)
    - role: zellij
      tags: [zellij]
      when: zellij_enabled | default(true)
    - role: zoxide
      tags: [zoxide]
      when: zoxide_enabled | default(true)
