---
# tasks file for zram

- name: Install zram-generator
  community.general.pacman:
    name: zram-generator
    state: latest

- name: Copy zram-generator.conf
  ansible.builtin.template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd daemon
