---
# defaults file for node

node_state: latest
node_npm_global_dir: /usr/local/lib/npm-global

node_global_packages:
  - name: "prettier"
  - name: "vscode-langservers-extracted"
  - name: "@ansible/ansible-language-server"
  - name: "dockerfile-language-server-nodejs"
  - name: "@microsoft/compose-language-service"
  - name: "typescript"
  - name: "typescript-language-server"
  - name: "svelte-language-server"
  - name: "typescript-svelte-plugin"
  - name: "yaml-language-server"
    version: "next"
