---
# tasks file for ansible

- name: Install Ansible
  community.general.pacman:
    name:
      - ansible
      - ansible-lint
    state: "{{ ansible_state }}"

- name: Install ansible language server
  kewlfft.aur.aur:
    name: ansible-language-server
    use: paru
    state: "{{ ansible_state }}"
  become: true
  become_user: aur_builder

- name: Ensure ansible config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/ansible"
    state: "{{ 'directory' if ansible_state == 'latest' else 'absent' }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
