---
# tasks file for virtmanager

- name: Install virt-manager
  community.general.pacman:
    name:
      - bridge-utils
      - dmidecode
      - dnsmasq
      - iptables-nft
      - libguestfs
      - libvirt
      - openbsd-netcat
      - qemu-full
      - vde2
      - virt-manager
      - virt-viewer
    state: "{{ virtmanager_state }}"

- name: Start and enable libvirtd service for LX
  ansible.builtin.service:
    name: libvirtd.service
    state: started
    enabled: true

- name: Start and enable libvirtd socket for QEMU
  ansible.builtin.service:
    name: libvirtd.socket
    state: started
    enabled: true

- name: Ensure unix_sock_group line is set
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#?unix_sock_group\s*='
    line: "unix_sock_group = 'libvirt'"
    backrefs: true
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Ensure unix_sock_rw_perms line is set
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#?unix_sock_rw_perms\s*='
    line: "unix_sock_rw_perms = '0770'"
    backrefs: true
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Ensure user is set in qemu.conf
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^#?user\s*='
    line: 'user = "{{ username }}"'
    backrefs: true
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Ensure group is set in qemu.conf
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^#?group\s*='
    line: 'group = "{{ username }}"'
    backrefs: true
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'