---
# defaults file for go

go_enabled: true
go_state: latest
go_gopath_dir: /usr/local/lib/go

go_tools:
  - golang.org/x/tools/gopls@latest
  - github.com/go-delve/delve/cmd/dlv@latest
  - golang.org/x/tools/cmd/goimports@latest
  - github.com/fatih/gomodifytags@latest
  - github.com/cweill/gotests/gotests@latest
  - github.com/kisielk/errcheck@latest
  - github.com/josharian/impl@latest
  - honnef.co/go/tools/cmd/staticcheck@latest
  - honnef.co/go/tools/cmd/structlayout@latest
